### ISSUE TITLE
Window

### ISSUE THREAD

**Issue by Gerben-Vogelaar** [CPNModeller/CPNModeller#2]
create window contains all different GUI components:
MenuBar, Toolbar, DeclerationsPanel, GraphEditor

**Comment by maartenflippo** [comment]
I created a startup class that sets the look and feel of the application to the style of the system that is running it. Creating the window can now be done [here](https://github.com/CPNModeller/CPNModeller/blob/87d92bd88b5cefe6c44406824b3219b3a6e0c607/src/main/java/cpnmodeller/Startup.java#L7).

**Comment by maartenflippo** [comment]
For the main container, I think we should use a [JSplitPane](https://docs.oracle.com/javase/8/docs/api/javax/swing/JSplitPane.html), as it does exactly what we wanted.
